server:  
  port: 9082

#logging:
#  level:
#    org.springframework: DEBUG

    
spring: 
  thymeleaf:  
    cache:  false 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 
  application: 
    name: hello-service

  
  
